import type { ConflictItem, Database, FieldOption, OutboxOperation, SourceConnection, SyncRun } from "./types";

const capturedAt = "2026-04-15T00:00:00-04:00";

const priority: FieldOption[] = [
  { name: "Low", color: "gold" },
  { name: "Medium", color: "amber" },
  { name: "High", color: "red" },
];

const clientStatuses: FieldOption[] = [
  { name: "New Lead", color: "gray", group: "to_do" },
  { name: "Contacting", color: "brown", group: "to_do" },
  { name: "In Conversation", color: "violet", group: "in_progress" },
  { name: "Qualified", color: "gold", group: "in_progress" },
  { name: "Active Client", color: "green", group: "in_progress" },
  { name: "Not Ready", color: "amber", group: "complete" },
  { name: "Inactive Client", color: "blue", group: "complete" },
  { name: "Lost", color: "red", group: "complete" },
];

const dealStages: FieldOption[] = [
  { name: "Lead", color: "gray", group: "to_do" },
  { name: "Discovery", color: "violet", group: "to_do" },
  { name: "Qualified", color: "brown", group: "in_progress" },
  { name: "Proposal", color: "gold", group: "in_progress" },
  { name: "Negotiation", color: "amber", group: "in_progress" },
  { name: "Active", color: "blue", group: "complete" },
  { name: "Complete", color: "green", group: "complete" },
  { name: "Lost", color: "red", group: "complete" },
];

const projectStatuses: FieldOption[] = [
  { name: "Not started", color: "gray", group: "to_do" },
  { name: "In progress", color: "blue", group: "in_progress" },
  { name: "Awaiting Review", color: "green", group: "complete" },
];

const assetStatuses: FieldOption[] = [
  { name: "Not started", color: "gray", group: "to_do" },
  { name: "1st draft", color: "brown", group: "in_progress" },
  { name: "In progress", color: "blue", group: "in_progress" },
  { name: "2nd draft", color: "gold", group: "in_progress" },
  { name: "Waiting for approval", color: "violet", group: "in_progress" },
  { name: "Final version", color: "green", group: "complete" },
];

const source = (id: string, url: string, collectionId: string, writeback: "supported" | "explicit-only" | "read-only" | "planned" = "supported") => ({
  type: "notion" as const,
  id,
  url,
  collectionId,
  capturedAt,
  writeback,
});

const driveSource = (id: string, url: string) => ({
  type: "google-drive" as const,
  id,
  url,
  capturedAt,
  writeback: "explicit-only" as const,
});

const gmailSource = (id: string, url: string) => ({
  type: "gmail" as const,
  id,
  url,
  capturedAt,
  writeback: "explicit-only" as const,
});

const calendarSource = (id: string, url: string) => ({
  type: "google-calendar" as const,
  id,
  url,
  capturedAt,
  writeback: "supported" as const,
});

export const mabDatabases: Database[] = [
  {
    id: "clients",
    name: "Clients",
    shortName: "CRM",
    category: "Sales CRM",
    source: "Notion database: Clients",
    description: "MAB account list with Notion-native statuses, lead sources, tags, relations, and call prep context.",
    sync: {
      sourceType: "notion",
      sourceId: "collection://30ee7d75-e286-8154-8ad3-000b8c34934e",
      sourceUrl: "https://www.notion.so/30ee7d75e2868173a457dcd64ffc0e8a",
      state: "snapshot",
      lastSyncedAt: capturedAt,
      writeback: "supported",
      notes: "Schema mirrored from the MAB AI Strategies teamspace. Records are connector snapshots until OAuth is installed.",
    },
    fields: [
      { key: "company", label: "Company", type: "title", width: 220, sourceKey: "Company" },
      { key: "contact", label: "Contact Person", type: "text", width: 170, sourceKey: "Contact Person" },
      { key: "status", label: "Status", type: "status", options: clientStatuses, width: 150, sourceKey: "Status" },
      { key: "priority", label: "Priority", type: "select", options: priority, width: 120, sourceKey: "Priority" },
      {
        key: "tags",
        label: "Tags",
        type: "multi",
        width: 220,
        sourceKey: "Tags",
        options: [
          "Marketing",
          "SMB",
          "Enterprise",
          "Management Consulting",
          "Engineering",
          "IT Consulting",
          "Mid-size",
          "Accounting",
          "Startup",
          "Legal",
          "Design",
          "Data Analysis",
          "Finance",
        ].map((name, index) => ({ name, color: ["pink", "gold", "gray", "violet", "brown", "amber", "blue", "gray", "red", "amber", "gray", "red", "blue"][index] })),
      },
      { key: "leadSource", label: "Lead Source", type: "select", sourceKey: "Lead Source", options: ["Referral", "Website", "Social Media", "Event", "In Network"].map((name, index) => ({ name, color: ["red", "blue", "violet", "amber", "pink"][index] })) },
      { key: "lastContact", label: "Last Contact", type: "date", sourceKey: "Last Contact" },
      { key: "email", label: "Email", type: "email", sourceKey: "Email" },
      { key: "website", label: "Website", type: "url", sourceKey: "Website" },
      { key: "service", label: "Type of Service", type: "text", width: 240, sourceKey: "Type of Service" },
      { key: "brief", label: "Client Brief", type: "text", width: 360, sourceKey: "Client Brief", readOnly: true },
    ],
    views: [
      { id: "contacts", name: "Contacts", type: "table", fields: ["company", "contact", "status", "priority", "tags", "lastContact"] },
      { id: "by-status", name: "By Status", type: "board", fields: ["company", "contact", "email", "priority"], groupBy: "status" },
      { id: "priority", name: "Priority", type: "table", fields: ["company", "status", "priority", "contact", "lastContact"], groupBy: "priority" },
      { id: "cards", name: "Account Cards", type: "gallery", fields: ["company", "brief", "tags", "status", "priority"] },
    ],
    records: [
      {
        id: "client-zp-holdings",
        company: "ZP Holdings",
        contact: "",
        status: "In Conversation",
        priority: "High",
        tags: ["Enterprise", "Management Consulting", "Data Analysis"],
        leadSource: "In Network",
        lastContact: "2026-03-29",
        email: "",
        website: "",
        service: "AI growth and infrastructure advisory",
        brief: "Pulled from the Clients database search result in MAB AI Strategies. Treat as an active account to enrich through the next live Notion sync.",
        _source: source("332e7d75e2868045ade6de6632961a6f", "https://www.notion.so/332e7d75e2868045ade6de6632961a6f", "collection://30ee7d75-e286-8154-8ad3-000b8c34934e"),
      },
      {
        id: "client-industrial-midwest",
        company: "Industrial Midwest Manufacturing Cohort",
        contact: "Operations buyers",
        status: "Qualified",
        priority: "High",
        tags: ["Engineering", "Mid-size", "Data Analysis"],
        leadSource: "Website",
        lastContact: "2026-04-09",
        email: "",
        website: "",
        service: "AI readiness audit and legacy infrastructure automation",
        brief: "Derived from the Drive strategy docs: Indiana/Iowa/Ohio manufacturers with legacy ERP, PBX, and labor-shortage pressure are the strongest consulting-led beachhead.",
        _source: driveSource("1LMNKxvDicCfLAbFwas7qvfQCbwBfLpsvTSC9JSFon3Y", "https://docs.google.com/document/d/1LMNKxvDicCfLAbFwas7qvfQCbwBfLpsvTSC9JSFon3Y"),
      },
      {
        id: "client-sunbelt-healthcare",
        company: "Sunbelt Healthcare and DSO Cohort",
        contact: "Clinic operators",
        status: "New Lead",
        priority: "Medium",
        tags: ["Legal", "Startup", "Marketing"],
        leadSource: "Social Media",
        lastContact: "2026-04-11",
        email: "",
        website: "",
        service: "HIPAA-aware voice agent and intake automation",
        brief: "GTM material points to dental and healthcare operators in Texas/Arizona as high-fit speed-to-lead targets.",
        _source: driveSource("1LMNKxvDicCfLAbFwas7qvfQCbwBfLpsvTSC9JSFon3Y", "https://docs.google.com/document/d/1LMNKxvDicCfLAbFwas7qvfQCbwBfLpsvTSC9JSFon3Y"),
      },
    ],
    template: { company: "New company", contact: "", status: "New Lead", priority: "Medium", tags: [], leadSource: "Referral", lastContact: "2026-04-15", email: "", website: "", service: "", brief: "" },
  },
  {
    id: "deals",
    name: "Deals",
    shortName: "Deals",
    category: "Sales CRM",
    source: "Notion database: Deals",
    description: "Pipeline opportunities mirrored from Notion plus MAB strategy-derived offers and proposal work.",
    sync: {
      sourceType: "notion",
      sourceId: "collection://30ee7d75-e286-819b-9361-000b2c683069",
      sourceUrl: "https://www.notion.so/30ee7d75e286816e9cf3ed8a04698517",
      state: "snapshot",
      lastSyncedAt: capturedAt,
      writeback: "supported",
      notes: "Notion status groups and board pipeline preserved.",
    },
    fields: [
      { key: "name", label: "Deal Name", type: "title", width: 260, sourceKey: "Deal Name" },
      { key: "stage", label: "Deal Stage", type: "status", options: dealStages, sourceKey: "Deal Stage" },
      { key: "value", label: "Deal Value", type: "currency", sourceKey: "Deal Value" },
      { key: "closeDate", label: "Close Date", type: "date", sourceKey: "Close Date" },
      { key: "priority", label: "Priority", type: "select", options: priority, sourceKey: "Priority" },
      { key: "source", label: "Source", type: "select", sourceKey: "Source", options: ["Inbound", "Referral", "LinkedIn", "Website", "Cold Outreach", "Returning Client"].map((name, index) => ({ name, color: ["gray", "pink", "brown", "green", "blue", "violet"][index] })) },
      { key: "client", label: "Clients", type: "relation", relationTo: "clients", sourceKey: "Clients" },
      { key: "next", label: "Next Step", type: "text", width: 320 },
    ],
    views: [
      { id: "deals", name: "Deals", type: "table", fields: ["name", "stage", "value", "closeDate", "priority", "source"] },
      { id: "pipeline", name: "Pipeline", type: "board", fields: ["name", "value", "priority", "closeDate"], groupBy: "stage", sortBy: "closeDate" },
      { id: "profit", name: "Yearly Profit", type: "table", fields: ["name", "value", "stage", "client", "closeDate"], filter: { field: "stage", value: "Active" } },
    ],
    records: [
      { id: "deal-business-development", name: "Business Development & Strategy", stage: "Discovery", value: 25000, closeDate: "2026-04-30", priority: "High", source: "LinkedIn", client: "ZP Holdings", next: "Convert discovery notes into paid AI readiness audit scope.", _source: source("30ee7d75e286817abbcffb8f28a5a804", "https://www.notion.so/30ee7d75e286817abbcffb8f28a5a804", "collection://30ee7d75-e286-819b-9361-000b2c683069") },
      { id: "deal-web-app-development", name: "Web App Development", stage: "Proposal", value: 40000, closeDate: "2026-05-10", priority: "High", source: "Website", client: "Industrial Midwest Manufacturing Cohort", next: "Package zero-trust agent infrastructure as the premium tier.", _source: source("30ee7d75e2868179840eea63b7d6009e", "https://www.notion.so/30ee7d75e2868179840eea63b7d6009e", "collection://30ee7d75-e286-819b-9361-000b2c683069") },
      { id: "deal-copywriting", name: "Copywriting Services", stage: "Qualified", value: 8500, closeDate: "2026-04-24", priority: "Medium", source: "Cold Outreach", client: "Sunbelt Healthcare and DSO Cohort", next: "Use PASTOR/TRUST frameworks from Drive strategy doc for verticalized listings.", _source: source("30ee7d75e286814386a4c6a6672af2cb", "https://www.notion.so/30ee7d75e286814386a4c6a6672af2cb", "collection://30ee7d75-e286-819b-9361-000b2c683069") },
      { id: "deal-sow-proposals", name: "SOW & Proposal Templates", stage: "Active", value: 15000, closeDate: "2026-04-21", priority: "High", source: "Returning Client", client: "MAB AI Strategies", next: "Turn calendar work block into reusable SOW templates for consulting, automation, and ops excellence packages.", _source: calendarSource("fvvta0hgdp7vs0o1a5n7hi4ios", "https://www.google.com/calendar/event?eid=ZnZ2dGEwaGdkcDd2czBvMWE1bjdoaTRpb3MgYm9ja3JhdGhtYXJrMDQ4MEBt") },
    ],
    template: { name: "New deal", stage: "Lead", value: 0, closeDate: "2026-04-30", priority: "Medium", source: "Inbound", client: "", next: "" },
  },
  {
    id: "interactions",
    name: "Interactions",
    shortName: "Calls",
    category: "Sales CRM",
    source: "Notion database: Interactions, Gmail, Calendar",
    description: "Client touchpoints, workspace signals, meetings, and follow-up decisions.",
    sync: {
      sourceType: "notion",
      sourceId: "collection://30ee7d75-e286-816e-a1e9-000b040b49e2",
      sourceUrl: "https://www.notion.so/30ee7d75e28681699a1ed6149f4acd7d",
      state: "snapshot",
      lastSyncedAt: capturedAt,
      writeback: "supported",
      notes: "Notion is editable. Gmail draft/label actions are explicit-only.",
    },
    fields: [
      { key: "name", label: "Name", type: "title", width: 260, sourceKey: "Name" },
      { key: "type", label: "Type", type: "select", sourceKey: "Type", options: ["Presentation", "Note", "Email", "Call", "Message", "Meeting", "Follow-Up"].map((name, index) => ({ name, color: ["pink", "gold", "red", "violet", "blue", "amber", "green"][index] })) },
      { key: "date", label: "Date", type: "datetime", sourceKey: "Date" },
      { key: "scope", label: "Internal / External", type: "select", sourceKey: "Internal / External", options: [{ name: "Internal", color: "green" }, { name: "External", color: "blue" }] },
      { key: "client", label: "Client", type: "relation", relationTo: "clients", sourceKey: "Client" },
      { key: "deal", label: "Deal", type: "relation", relationTo: "deals", sourceKey: "Deal" },
      { key: "outcome", label: "Outcome", type: "text", width: 360, sourceKey: "Outcome" },
      { key: "followup", label: "Follow-up Required", type: "checkbox", sourceKey: "Follow-up Required" },
      { key: "location", label: "Location", type: "text", sourceKey: "Location" },
    ],
    views: [
      { id: "recent", name: "Recent", type: "list", fields: ["name", "date", "type", "scope", "outcome"], groupBy: "date", sortBy: "date" },
      { id: "calendar", name: "Calendar", type: "calendar", fields: ["name", "type", "client"], sortBy: "date" },
      { id: "all", name: "All Interactions", type: "table", fields: ["name", "date", "type", "scope", "client", "followup"] },
    ],
    records: [
      { id: "interaction-sow-calendar", name: "Biz Ops - SOW & Proposal Templates", type: "Meeting", date: "2026-04-14T10:00:00-04:00", scope: "Internal", client: "MAB AI Strategies", deal: "SOW & Proposal Templates", outcome: "Build and refine SOW and proposal templates for AI-driven sales, automation, and operational excellence packages.", followup: true, location: "Google Calendar", _source: calendarSource("fvvta0hgdp7vs0o1a5n7hi4ios", "https://www.google.com/calendar/event?eid=ZnZ2dGEwaGdkcDd2czBvMWE1bjdoaTRpb3MgYm9ja3JhdGhtYXJrMDQ4MEBt") },
      { id: "interaction-gtm-chat", name: "Google Chat GTM strategy bundle", type: "Message", date: "2026-04-11T14:25:21-04:00", scope: "Internal", client: "MAB AI Strategies", deal: "Business Development & Strategy", outcome: "Chat notification referenced GTM, defensibility analysis, marketplace profile work, lead gen that lives on the laptop, and GitHub godmode ideas.", followup: true, location: "Gmail / Google Chat", _source: gmailSource("19d7dca96c8c52ef", "https://mail.google.com/mail/#all/19d7dca96c8c52ef") },
      { id: "interaction-openhands", name: "OpenHands follow-up for MAB event", type: "Email", date: "2026-04-06T14:34:07-04:00", scope: "External", client: "MAB AI Strategies", deal: "Web App Development", outcome: "OpenHands developer relations follow-up after Boston event signup; potential context for agent infrastructure tooling.", followup: true, location: "Gmail", _source: gmailSource("19d6412d66fd4c8b", "https://mail.google.com/mail/#all/19d6412d66fd4c8b") },
      { id: "interaction-bleu-horizon", name: "Bleu Horizon Onboarding Call", type: "Call", date: "2026-02-21", scope: "External", client: "ZP Holdings", deal: "Business Development & Strategy", outcome: "Notion interaction record with follow-up scheduling pattern and onboarding-call template structure.", followup: true, location: "Notion", _source: source("30ee7d75e28681c48b9fc7e3f08a38e8", "https://www.notion.so/30ee7d75e28681c48b9fc7e3f08a38e8", "collection://30ee7d75-e286-816e-a1e9-000b040b49e2") },
    ],
    template: { name: "New interaction", type: "Meeting", date: "2026-04-15", scope: "External", client: "", deal: "", outcome: "", followup: false, location: "" },
  },
  {
    id: "projects",
    name: "Projects",
    shortName: "Projects",
    category: "Delivery",
    source: "Notion database: Projects",
    description: "Execution workspace for agents, CRM builds, lead enrichment, and app infrastructure.",
    sync: {
      sourceType: "notion",
      sourceId: "collection://2ede7d75-e286-807c-9ee1-000b310c9070",
      sourceUrl: "https://www.notion.so/2ede7d75e28680a59825fb8fc6443fcf",
      state: "snapshot",
      lastSyncedAt: capturedAt,
      writeback: "supported",
      notes: "Projects live under The Lab and include app/agent build work.",
    },
    fields: [
      { key: "name", label: "Project name", type: "title", width: 300, sourceKey: "Project name" },
      { key: "status", label: "Status", type: "status", options: projectStatuses, sourceKey: "Status" },
      { key: "startDate", label: "Start date", type: "date", sourceKey: "Start date" },
      { key: "lastEdited", label: "Last Edited Date", type: "datetime", readOnly: true, sourceKey: "Last Edited Date" },
      { key: "attach", label: "Attach file", type: "file", sourceKey: "Attach file" },
      { key: "focus", label: "Focus", type: "text", width: 360 },
    ],
    views: [
      { id: "status", name: "By Status", type: "board", fields: ["name", "startDate", "focus"], groupBy: "status" },
      { id: "all", name: "All Projects", type: "table", fields: ["name", "status", "startDate", "lastEdited", "attach"] },
      { id: "delivery", name: "Delivery Briefs", type: "list", fields: ["name", "focus", "status", "startDate"], sortBy: "startDate" },
    ],
    records: [
      { id: "project-outreach-automation", name: "Project: Outreach Automation", status: "In progress", startDate: "2026-02-21", lastEdited: "2026-02-21T19:37:00Z", attach: "", focus: "Source raw leads, enrich them, and route into outbound systems such as Instantly and Seamless.", _source: source("304e7d75e28680228c5ae2099f357de2", "https://www.notion.so/304e7d75e28680228c5ae2099f357de2", "collection://2ede7d75-e286-807c-9ee1-000b310c9070") },
      { id: "project-crm-build", name: "Project: CRM Build - Github/Codex", status: "In progress", startDate: "2026-02-11", lastEdited: "2026-02-11T15:35:00Z", attach: "", focus: "Codex/GitHub implementation work around CRM structure and operating data.", _source: source("304e7d75e28680d09a7af8dd5b5a0d61", "https://www.notion.so/304e7d75e28680d09a7af8dd5b5a0d61", "collection://2ede7d75-e286-807c-9ee1-000b310c9070") },
      { id: "project-company-website", name: "Project: Company Website - Github/Codex", status: "Not started", startDate: "2026-02-11", lastEdited: "2026-02-11T15:35:00Z", attach: "", focus: "Company web presence and conversion path for MAB AI Strategies.", _source: source("304e7d75e28680dcb789f38d54d1734a", "https://www.notion.so/304e7d75e28680dcb789f38d54d1734a", "collection://2ede7d75-e286-807c-9ee1-000b310c9070") },
      { id: "project-lead-enrichment", name: "Lead Enrichment Tool", status: "In progress", startDate: "2026-02-11", lastEdited: "2026-02-11T15:33:00Z", attach: "", focus: "Waterfall enrichment, qualification, and lead scoring aligned with the Clay-style GTM strategy.", _source: source("304e7d75e2868040b95fcdcb250fc856", "https://www.notion.so/304e7d75e2868040b95fcdcb250fc856", "collection://2ede7d75-e286-807c-9ee1-000b310c9070") },
      { id: "project-workspace-flow-agent", name: "Workspace Flow Agent", status: "Awaiting Review", startDate: "2026-01-22", lastEdited: "2026-01-22T18:00:00Z", attach: "", focus: "Google Cloud-named agent for cross-workspace orchestration.", _source: source("2ede7d75e28680f7832ac50a98e4c141", "https://www.notion.so/2ede7d75e28680f7832ac50a98e4c141", "collection://2ede7d75-e286-807c-9ee1-000b310c9070") },
    ],
    template: { name: "New project", status: "Not started", startDate: "2026-04-15", lastEdited: "", attach: "", focus: "" },
  },
  {
    id: "assets",
    name: "Asset Library",
    shortName: "Assets",
    category: "Operations",
    source: "Notion database: Asset Library",
    description: "Reusable apps, workflows, agents, automations, SOPs, and implementation assets.",
    sync: {
      sourceType: "notion",
      sourceId: "collection://30de7d75-e286-80be-bc7d-000b64a85d9e",
      sourceUrl: "https://www.notion.so/30de7d75e286806dab18c99eebda38eb",
      state: "snapshot",
      lastSyncedAt: capturedAt,
      writeback: "supported",
      notes: "Media files are indexed by source metadata and kept read-only until Drive/R2 storage is configured.",
    },
    fields: [
      { key: "name", label: "Asset name", type: "title", width: 260, sourceKey: "Asset name" },
      { key: "type", label: "Asset type", type: "multi", sourceKey: "Asset type", options: ["Plugin", "Framework", "Skill", "Automation", "Agent", "Workflow"].map((name, index) => ({ name, color: ["violet", "gold", "gray", "blue", "amber", "green"][index] })) },
      { key: "status", label: "Status", type: "status", options: assetStatuses, sourceKey: "Status" },
      { key: "url", label: "Asset URL", type: "url", sourceKey: "Asset URL" },
      { key: "description", label: "Asset description", type: "text", width: 360, sourceKey: "Asset description" },
      { key: "created", label: "Creation Date", type: "date", sourceKey: "Creation Date" },
      { key: "designer", label: "Designer", type: "person", sourceKey: "Designer" },
    ],
    views: [
      { id: "all", name: "All Assets", type: "table", fields: ["name", "type", "status", "url", "description", "created"] },
      { id: "gallery", name: "Gallery", type: "gallery", fields: ["name", "status", "type", "description"] },
      { id: "mine", name: "My Assets", type: "table", fields: ["name", "url", "description", "type", "status", "created"] },
    ],
    records: [
      { id: "asset-heat-map", name: "Heat Map/Lead Generation Workflow", type: ["Workflow", "Automation"], status: "In progress", url: "https://www.notion.so/32ee7d75e286807aa391df64df5c2a95", description: "Lead-generation workflow asset surfaced from the Notion Asset Library.", created: "2026-03-25", designer: "Mark", _source: source("32ee7d75e286807aa391df64df5c2a95", "https://www.notion.so/32ee7d75e286807aa391df64df5c2a95", "collection://30de7d75-e286-80be-bc7d-000b64a85d9e") },
      { id: "asset-proposal-generator", name: "Proposal Generator", type: ["Agent", "Workflow"], status: "In progress", url: "https://www.notion.so/32ee7d75e286802da6a4f21e838dc377", description: "Proposal-generator asset that should connect to SOW template work and deal records.", created: "2026-03-25", designer: "Mark", _source: source("32ee7d75e286802da6a4f21e838dc377", "https://www.notion.so/32ee7d75e286802da6a4f21e838dc377", "collection://30de7d75-e286-80be-bc7d-000b64a85d9e") },
      { id: "asset-job-automation", name: "Job Hunting Automation Workflow", type: ["Automation", "Workflow"], status: "2nd draft", url: "https://www.notion.so/30de7d75e2868142b06ad6bd6bcdfa13", description: "Repeatable workflow asset drafted in ChatGPT and stored in Notion.", created: "2026-02-20", designer: "Mark", _source: source("30de7d75e2868142b06ad6bd6bcdfa13", "https://www.notion.so/30de7d75e2868142b06ad6bd6bcdfa13", "collection://30de7d75-e286-80be-bc7d-000b64a85d9e") },
      { id: "asset-build-companion", name: "Build Companion Classic", type: ["Agent", "Skill"], status: "Final version", url: "https://www.notion.so/398a678f2a9c4e33b8735d0d37741b94", description: "Companion asset for build workflows.", created: "2026-03-13", designer: "Mark", _source: source("398a678f2a9c4e33b8735d0d37741b94", "https://www.notion.so/398a678f2a9c4e33b8735d0d37741b94", "collection://30de7d75-e286-80be-bc7d-000b64a85d9e") },
    ],
    template: { name: "New asset", type: ["Workflow"], status: "Not started", url: "", description: "", created: "2026-04-15", designer: "Mark" },
  },
  {
    id: "tools",
    name: "CRM Sales Tools",
    shortName: "Tools",
    category: "Operations",
    source: "Notion database: CRM Sales Tools",
    description: "Prospecting, CRM, outreach, and analytics tools with subscription, integration, and rotation metadata. Secrets are redacted.",
    sync: {
      sourceType: "notion",
      sourceId: "collection://0f7b709d-f472-4883-af36-0c86b439e0d7",
      sourceUrl: "https://www.notion.so/64458b1cdd2d44ceba3d7aae1f60dd78",
      state: "snapshot",
      lastSyncedAt: capturedAt,
      writeback: "supported",
      notes: "API Key values are intentionally never mirrored into the app UI.",
    },
    fields: [
      { key: "name", label: "Tool Name", type: "title", width: 220, sourceKey: "Tool Name" },
      { key: "schedule", label: "Automation Schedule", type: "select", sourceKey: "Automation Schedule", options: ["Prospecting", "Outreach", "Analytics", "CRM", "Other"].map((name, index) => ({ name, color: ["red", "gold", "blue", "pink", "violet"][index] })) },
      { key: "integrations", label: "Integrations", type: "multi", sourceKey: "Integrations", options: ["Salesforce", "LinkedIN", "Claude", "Zapier", "Notion", "Google Sheets", "Google Calendar", "Gmail", "Hubspot"].map((name, index) => ({ name, color: ["brown", "red", "blue", "pink", "gray", "green", "violet", "gold", "amber"][index] })) },
      { key: "credits", label: "Subscription Credits", type: "number", sourceKey: "Subscription Credits" },
      { key: "cost", label: "Subscription Cost", type: "currency", sourceKey: "Subscription Cost" },
      { key: "created", label: "Date Created", type: "date", sourceKey: "Date Created" },
      { key: "expires", label: "Expiration Date", type: "date", sourceKey: "Expiration Date" },
      { key: "api", label: "API Key", type: "text", readOnly: true, sourceKey: "API Key" },
    ],
    views: [
      { id: "all", name: "All Tools", type: "table", fields: ["name", "api", "credits", "cost", "expires", "schedule", "integrations", "created"] },
      { id: "schedule", name: "By Schedule", type: "board", fields: ["name", "cost", "expires", "integrations"], groupBy: "schedule" },
    ],
    records: [
      { id: "tool-apollo", name: "Apollo.io (Prospecting)", schedule: "Prospecting", integrations: ["LinkedIN", "Google Sheets"], credits: 0, cost: 0, created: "2026-02-17", expires: "2026-05-17", api: "redacted", _source: source("2f7e7d75e286801681c0f6c8b7356f8a", "https://www.notion.so/2f7e7d75e286801681c0f6c8b7356f8a", "collection://0f7b709d-f472-4883-af36-0c86b439e0d7") },
      { id: "tool-pipedrive", name: "Pipedrive (CRM)", schedule: "CRM", integrations: ["Hubspot", "Zapier"], credits: 0, cost: 0, created: "2026-02-17", expires: "2026-05-17", api: "redacted", _source: source("2f8e7d75e286804cb940dd3526a8d27f", "https://www.notion.so/2f8e7d75e286804cb940dd3526a8d27f", "collection://0f7b709d-f472-4883-af36-0c86b439e0d7") },
      { id: "tool-seamless", name: "Seamless.ai (Prospecting)", schedule: "Prospecting", integrations: ["LinkedIN", "Google Sheets"], credits: 0, cost: 0, created: "2026-02-17", expires: "2026-05-17", api: "pending sales team", _source: source("2f8e7d75e2868096983ce11b08f62285", "https://www.notion.so/2f8e7d75e2868096983ce11b08f62285", "collection://0f7b709d-f472-4883-af36-0c86b439e0d7") },
      { id: "tool-snov", name: "snov.io", schedule: "Outreach", integrations: ["Gmail", "Google Sheets"], credits: 0, cost: 0, created: "2026-02-17", expires: "2026-05-17", api: "redacted", _source: source("2f8e7d75e2868057ae3bd2d6c30ccbdf", "https://www.notion.so/2f8e7d75e2868057ae3bd2d6c30ccbdf", "collection://0f7b709d-f472-4883-af36-0c86b439e0d7") },
    ],
    template: { name: "New tool", schedule: "CRM", integrations: ["Notion"], credits: 0, cost: 0, created: "2026-04-15", expires: "2026-06-15", api: "redacted" },
  },
  {
    id: "workspace-docs",
    name: "Workspace Intelligence",
    shortName: "Docs",
    category: "Knowledge",
    source: "Google Drive index",
    description: "Strategy docs, prospect databases, intake apps, org instructions, and reference artifacts from Drive.",
    sync: {
      sourceType: "google-drive",
      sourceId: "drive-search:MAB AI Strategies",
      state: "snapshot",
      lastSyncedAt: capturedAt,
      writeback: "explicit-only",
      notes: "Drive files are indexed as records with extracted context. Full document edits stay explicit.",
    },
    fields: [
      { key: "title", label: "Title", type: "title", width: 320 },
      { key: "kind", label: "Kind", type: "select", options: ["Doc", "Sheet", "PDF", "HTML", "Markdown"].map((name, index) => ({ name, color: ["blue", "green", "red", "amber", "gray"][index] })) },
      { key: "domain", label: "Operating Domain", type: "multi", options: ["GTM", "Lead Gen", "OpenClaw", "CRM", "Org", "Intake", "Research", "Pricing"].map((name, index) => ({ name, color: ["green", "blue", "red", "pink", "gray", "amber", "violet", "gold"][index] })) },
      { key: "updated", label: "Updated", type: "datetime" },
      { key: "url", label: "Source URL", type: "url" },
      { key: "summary", label: "Use in App", type: "text", width: 440 },
    ],
    views: [
      { id: "all", name: "All Files", type: "table", fields: ["title", "kind", "domain", "updated", "url"] },
      { id: "domains", name: "By Domain", type: "board", fields: ["title", "kind", "updated", "summary"], groupBy: "kind" },
      { id: "briefs", name: "Briefs", type: "list", fields: ["title", "summary", "domain", "updated"] },
    ],
    records: [
      { id: "doc-fiverr-growth", title: "Strategic Fiverr AI Growth Plan", kind: "Doc", domain: ["GTM", "OpenClaw", "Pricing"], updated: "2026-04-09T15:36:17Z", url: "https://docs.google.com/document/d/1LMNKxvDicCfLAbFwas7qvfQCbwBfLpsvTSC9JSFon3Y", summary: "Primary strategy source: high-ticket consulting, zero-trust AI infrastructure, vertical beachheads, pricing tiers, and GTM copy frameworks.", _source: driveSource("1LMNKxvDicCfLAbFwas7qvfQCbwBfLpsvTSC9JSFon3Y", "https://docs.google.com/document/d/1LMNKxvDicCfLAbFwas7qvfQCbwBfLpsvTSC9JSFon3Y") },
      { id: "doc-rust-belt", title: "Indiana Rust Belt B2B Prospect Database for MAB AI Strategies LLC", kind: "Doc", domain: ["Lead Gen", "Research"], updated: "2026-04-09", url: "https://docs.google.com/document/d/1V7pg5-dYhTScCgY2QWQtzLOEPG3qi9Cccm5XIkSgnA4", summary: "Prospect targeting source for manufacturing, logistics, operations, and legacy infrastructure opportunities.", _source: driveSource("1V7pg5-dYhTScCgY2QWQtzLOEPG3qi9Cccm5XIkSgnA4", "https://docs.google.com/document/d/1V7pg5-dYhTScCgY2QWQtzLOEPG3qi9Cccm5XIkSgnA4") },
      { id: "sheet-master-merged", title: "Master_Merged.xlsx", kind: "Sheet", domain: ["Lead Gen", "CRM"], updated: "2026-04-09", url: "https://drive.google.com/file/d/17kQ1s3r-ETAxUGR4wlTf83U1lx_bDPt3", summary: "Candidate source for spreadsheet-to-collection ingestion once the Sheets adapter is authorized.", _source: driveSource("17kQ1s3r-ETAxUGR4wlTf83U1lx_bDPt3", "https://drive.google.com/file/d/17kQ1s3r-ETAxUGR4wlTf83U1lx_bDPt3") },
      { id: "sheet-sales-pro", title: "*Sales Pro v0.13", kind: "Sheet", domain: ["Lead Gen", "CRM"], updated: "2026-04-09", url: "https://docs.google.com/spreadsheets/d/1ZJP9c7wKDZRNeJkhvLtcLs6zfRw3-41_RE4eLGJFfZw", summary: "Sales tooling sheet to become a structured collection after header inference.", _source: driveSource("1ZJP9c7wKDZRNeJkhvLtcLs6zfRw3-41_RE4eLGJFfZw", "https://docs.google.com/spreadsheets/d/1ZJP9c7wKDZRNeJkhvLtcLs6zfRw3-41_RE4eLGJFfZw") },
      { id: "md-vp-instructions", title: "MAB_AI_VP_Custom_Instructions.md", kind: "Markdown", domain: ["Org", "Research"], updated: "2026-04-09", url: "https://drive.google.com", summary: "Operating instructions for MAB AI VP behavior and internal agent context.", _source: driveSource("drive-search:MAB_AI_VP_Custom_Instructions.md", "https://drive.google.com") },
      { id: "html-intake-app", title: "MAB_AI_Intake_App.html", kind: "HTML", domain: ["Intake", "CRM"], updated: "2026-04-09", url: "https://drive.google.com", summary: "Existing intake app artifact that should be linked to client onboarding and lead capture flows.", _source: driveSource("drive-search:MAB_AI_Intake_App.html", "https://drive.google.com") },
    ],
    template: { title: "New artifact", kind: "Doc", domain: ["Research"], updated: "2026-04-15", url: "", summary: "" },
  },
  {
    id: "agent-teams",
    name: "Agent Teams",
    shortName: "Agents",
    category: "AI Ops",
    source: "Notion database: Agent Teams and Prompts page",
    description: "Agent roster, platforms, skills, tools, APIs, and persona prompts from the MAB workspace.",
    sync: {
      sourceType: "notion",
      sourceId: "collection://32de7d75-e286-80a5-b08a-c59657a4c453",
      sourceUrl: "https://www.notion.so/32de7d75e28680a5b08ac59657a4c453",
      state: "snapshot",
      lastSyncedAt: capturedAt,
      writeback: "supported",
      notes: "Schema discovered from Agent Teams. Prompt entries are represented as launchable agent records.",
    },
    fields: [
      { key: "agent", label: "Agent Name", type: "title", width: 220 },
      { key: "status", label: "Status", type: "status", options: ["Development", "Active", "Paused", "Archived"].map((name, index) => ({ name, color: ["gold", "green", "amber", "gray"][index], group: index === 1 ? "in_progress" : index === 3 ? "complete" : "to_do" })) },
      { key: "goal", label: "Primary Goal", type: "text", width: 360 },
      { key: "platforms", label: "Platforms", type: "multi", options: ["Discord", "Slack", "Web", "Twitter", "GitHub", "Telegram", "WhatsApp", "API", "CLI", "Mobile", "Apollo", "Claude.ai"].map((name, index) => ({ name, color: ["violet", "green", "blue", "red", "gray", "blue", "green", "gold", "gray", "pink", "amber", "violet"][index] })) },
      { key: "tools", label: "Tools", type: "multi", options: ["LangChain", "CrewAI", "LlamaIndex", "OpenAI API", "Anthropic API", "Custom Framework", "Apollo.io"].map((name, index) => ({ name, color: ["blue", "green", "gold", "gray", "violet", "amber", "red"][index] })) },
      { key: "skills", label: "Skills", type: "multi", options: ["Data Analysis", "Content Creation", "Code Generation", "Research", "Problem Solving", "Communication", "Project Management", "Quality Assurance", "Design"].map((name, index) => ({ name, color: ["red", "pink", "gray", "violet", "amber", "green", "blue", "gold", "gray"][index] })) },
      { key: "lastActive", label: "Last Active", type: "datetime" },
    ],
    views: [
      { id: "all", name: "All Teams", type: "table", fields: ["agent", "status", "goal", "platforms", "skills", "lastActive"] },
      { id: "active", name: "Active Teams", type: "board", fields: ["agent", "goal", "platforms", "skills"], groupBy: "status" },
      { id: "matrix", name: "Skills Matrix", type: "gallery", fields: ["agent", "status", "goal", "skills"] },
    ],
    records: [
      { id: "agent-atlas", agent: "Atlas", status: "Active", goal: "Rapid operating-mode agent for offer maps, archive decisions, and revenue actions.", platforms: ["Web", "CLI", "Claude.ai"], tools: ["OpenAI API", "Anthropic API", "Custom Framework"], skills: ["Research", "Problem Solving", "Project Management"], lastActive: "2026-04-11", _source: source("2e1e7d75e28680d592a5f7d86408c886", "https://www.notion.so/2e1e7d75e28680d592a5f7d86408c886", "prompts-page", "planned") },
      { id: "agent-iron-mary", agent: "Iron Mary", status: "Development", goal: "One of the named MAB agent concepts from the Prompts page roster.", platforms: ["Web", "API"], tools: ["Custom Framework"], skills: ["Communication", "Research"], lastActive: "2026-04-11", _source: source("2e1e7d75e28680d592a5f7d86408c886", "https://www.notion.so/2e1e7d75e28680d592a5f7d86408c886", "prompts-page", "planned") },
      { id: "agent-wire", agent: "Wire", status: "Development", goal: "Signal-gathering and workspace routing concept from the Prompts page.", platforms: ["Gmail", "Google Calendar", "API"], tools: ["OpenAI API", "Custom Framework"], skills: ["Data Analysis", "Research", "Communication"], lastActive: "2026-04-11", _source: source("2e1e7d75e28680d592a5f7d86408c886", "https://www.notion.so/2e1e7d75e28680d592a5f7d86408c886", "prompts-page", "planned") },
      { id: "agent-blueprint", agent: "Blueprint", status: "Paused", goal: "Architecture/planning agent concept suited to SOW, proposal, and implementation map generation.", platforms: ["Web", "GitHub"], tools: ["Anthropic API", "Custom Framework"], skills: ["Project Management", "Design", "Code Generation"], lastActive: "2026-04-11", _source: source("2e1e7d75e28680d592a5f7d86408c886", "https://www.notion.so/2e1e7d75e28680d592a5f7d86408c886", "prompts-page", "planned") },
    ],
    template: { agent: "New agent", status: "Development", goal: "", platforms: ["Web"], tools: ["Custom Framework"], skills: ["Research"], lastActive: "2026-04-15" },
  },
  {
    id: "tasks",
    name: "Todo List",
    shortName: "Tasks",
    category: "Execution",
    source: "Notion database: Todo List",
    description: "Immediate execution queue synthesized from Notion task structure, calendar blocks, and implementation follow-ups.",
    sync: {
      sourceType: "notion",
      sourceId: "collection://2a5e7d75-e286-80d4-932f-f749e287e368",
      sourceUrl: "https://www.notion.so/2a5e7d75e28680d4932ff749e287e368",
      state: "snapshot",
      lastSyncedAt: capturedAt,
      writeback: "supported",
      notes: "Uses Notion fields To-do item, Assignee, Priority, Status, Due date.",
    },
    fields: [
      { key: "task", label: "To-do item", type: "title", width: 320 },
      { key: "assignee", label: "Assignee", type: "person" },
      { key: "priority", label: "Priority", type: "select", options: priority },
      { key: "status", label: "Status", type: "status", options: [{ name: "Not started", color: "gray", group: "to_do" }, { name: "In progress", color: "blue", group: "in_progress" }, { name: "Done", color: "green", group: "complete" }] },
      { key: "dueDate", label: "Due date", type: "date" },
      { key: "related", label: "Related System", type: "relation" },
    ],
    views: [
      { id: "todo", name: "To Do", type: "table", fields: ["task", "status", "priority", "dueDate", "related"] },
      { id: "priority", name: "By Priority", type: "board", fields: ["task", "status", "dueDate", "related"], groupBy: "priority" },
      { id: "calendar", name: "Calendar", type: "calendar", fields: ["task", "priority", "status"], sortBy: "dueDate" },
    ],
    records: [
      { id: "task-oauth", task: "Install Cloudflare OAuth credentials for Notion and Google APIs", assignee: "Mark", priority: "High", status: "Not started", dueDate: "2026-04-16", related: "Cloudflare Sync", _source: { type: "local", id: "implementation-task-oauth", capturedAt, writeback: "planned" } },
      { id: "task-sheets", task: "Infer headers for Master_Merged and Sales Pro sheets", assignee: "Mark", priority: "Medium", status: "Not started", dueDate: "2026-04-18", related: "Workspace Intelligence", _source: driveSource("17kQ1s3r-ETAxUGR4wlTf83U1lx_bDPt3", "https://drive.google.com/file/d/17kQ1s3r-ETAxUGR4wlTf83U1lx_bDPt3") },
      { id: "task-proposals", task: "Turn SOW calendar block into proposal generator inputs", assignee: "Mark", priority: "High", status: "In progress", dueDate: "2026-04-21", related: "SOW & Proposal Templates", _source: calendarSource("fvvta0hgdp7vs0o1a5n7hi4ios", "https://www.google.com/calendar/event?eid=ZnZ2dGEwaGdkcDd2czBvMWE1bjdoaTRpb3MgYm9ja3JhdGhtYXJrMDQ4MEBt") },
    ],
    template: { task: "New task", assignee: "Mark", priority: "Medium", status: "Not started", dueDate: "2026-04-30", related: "" },
  },
  {
    id: "workspace-signals",
    name: "Workspace Signals",
    shortName: "Signals",
    category: "Execution",
    source: "Gmail and Google Calendar",
    description: "Inbox, chat, receipt, and calendar signals that should become CRM actions or operating records.",
    sync: {
      sourceType: "gmail",
      sourceId: "gmail-query:\"MAB AI Strategies\" newer_than:180d",
      state: "snapshot",
      lastSyncedAt: capturedAt,
      writeback: "explicit-only",
      notes: "Gmail writes are draft/label only and require explicit user action.",
    },
    fields: [
      { key: "subject", label: "Subject", type: "title", width: 360 },
      { key: "sourceKind", label: "Source", type: "select", options: [{ name: "Gmail", color: "red" }, { name: "Calendar", color: "blue" }, { name: "Google Chat", color: "green" }] },
      { key: "from", label: "From", type: "text" },
      { key: "received", label: "Received", type: "datetime" },
      { key: "labels", label: "Labels", type: "multi", options: ["INBOX", "UNREAD", "IMPORTANT", "SENT", "CATEGORY_UPDATES", "CATEGORY_PERSONAL"].map((name, index) => ({ name, color: ["blue", "gold", "red", "gray", "green", "violet"][index] })) },
      { key: "action", label: "Action", type: "text", width: 420 },
      { key: "url", label: "Open", type: "url" },
    ],
    views: [
      { id: "inbox", name: "Inbox Signals", type: "table", fields: ["subject", "sourceKind", "from", "received", "labels", "action"] },
      { id: "by-source", name: "By Source", type: "board", fields: ["subject", "received", "action"], groupBy: "sourceKind" },
      { id: "briefs", name: "Action Briefs", type: "list", fields: ["subject", "action", "received", "labels"] },
    ],
    records: [
      { id: "signal-sow-calendar", subject: "Notification: Biz Ops - SOW & Proposal Templates", sourceKind: "Calendar", from: "Google Calendar", received: "2026-04-14T13:30:14Z", labels: ["INBOX", "CATEGORY_UPDATES"], action: "Connect SOW/proposal template work to Deals, Assets, and Proposal Generator.", url: "https://mail.google.com/mail/#all/19d8c2f84dfab18c", _source: gmailSource("19d8c2f84dfab18c", "https://mail.google.com/mail/#all/19d8c2f84dfab18c") },
      { id: "signal-day-ahead", subject: "Your Day Ahead 04/12/2026", sourceKind: "Gmail", from: "bockrathmark0480+cc@gmail.com", received: "2026-04-12T11:00:01Z", labels: ["UNREAD", "SENT", "INBOX"], action: "Daily brief source can become a personal operations pane after business systems are stable.", url: "https://mail.google.com/mail/#all/19d81593866af975", _source: gmailSource("19d81593866af975", "https://mail.google.com/mail/#all/19d81593866af975") },
      { id: "signal-gtm-chat", subject: "Google Chat: MAB GTM and defensibility analysis", sourceKind: "Google Chat", from: "Mark Bockrath via Google Chat", received: "2026-04-11T18:25:21Z", labels: ["UNREAD", "INBOX", "CATEGORY_UPDATES"], action: "Index linked GTM docs, Fiverr/Upwork gig tooling, lead gen, Claude marketplace, and GitHub godmode references.", url: "https://mail.google.com/mail/#all/19d7dca96c8c52ef", _source: gmailSource("19d7dca96c8c52ef", "https://mail.google.com/mail/#all/19d7dca96c8c52ef") },
      { id: "signal-anthropic", subject: "Anthropic receipt", sourceKind: "Gmail", from: "Anthropic, PBC", received: "2026-03-26T04:28:11Z", labels: ["IMPORTANT", "INBOX", "CATEGORY_UPDATES"], action: "Classify as AI tooling expense and connect to CRM Sales Tools when accounting integration is added.", url: "https://mail.google.com/mail/#all/19d28666448cd845", _source: gmailSource("19d28666448cd845", "https://mail.google.com/mail/#all/19d28666448cd845") },
    ],
    template: { subject: "New signal", sourceKind: "Gmail", from: "", received: "2026-04-15", labels: ["INBOX"], action: "", url: "" },
  },
];

export const sourceConnections: SourceConnection[] = [
  { id: "notion", name: "Notion", state: "snapshot", detail: "MAB AI Strategies teamspace, owner access, schemas mirrored from live connector.", lastSyncedAt: capturedAt, recordCount: mabDatabases.filter((database) => database.sync.sourceType === "notion").reduce((sum, database) => sum + database.records.length, 0), writeback: "Records, properties, statuses, and relations after OAuth" },
  { id: "google-drive", name: "Google Drive", state: "snapshot", detail: "Strategy docs, prospect spreadsheets, intake apps, org files, and research artifacts indexed.", lastSyncedAt: capturedAt, recordCount: mabDatabases.find((database) => database.id === "workspace-docs")?.records.length ?? 0, writeback: "Explicit document actions only" },
  { id: "gmail", name: "Gmail", state: "snapshot", detail: "MAB-related inbox, Chat notifications, receipts, and calendar notifications indexed.", lastSyncedAt: capturedAt, recordCount: mabDatabases.find((database) => database.id === "workspace-signals")?.records.length ?? 0, writeback: "Drafts and labels only" },
  { id: "google-calendar", name: "Google Calendar", state: "snapshot", detail: "SOW/proposal business operations block mapped into deals, tasks, and interactions.", lastSyncedAt: capturedAt, recordCount: 2, writeback: "Event create/update after OAuth" },
  { id: "cloudflare", name: "Cloudflare", state: "connected", detail: "Worker, D1, KV, Queue, Cron, and workers.dev endpoint are live. R2 waits on account enablement.", lastSyncedAt: capturedAt, recordCount: 4, writeback: "Private sync API" },
  { id: "github", name: "GitHub", state: "connected", detail: "Public repo connected, branch pushed, and PR opened from the codex implementation branch.", lastSyncedAt: capturedAt, recordCount: 1, writeback: "Commit, push, and PR workflow" },
];

export const initialSyncRuns: SyncRun[] = [
  { id: "sync-notion-snapshot", source: "notion", status: "success", startedAt: "2026-04-15T00:00:00-04:00", finishedAt: "2026-04-15T00:03:00-04:00", recordsSeen: 32, message: "Connector snapshot captured MAB AI Strategies teamspace schemas, views, and representative records." },
  { id: "sync-drive-snapshot", source: "google-drive", status: "success", startedAt: "2026-04-15T00:03:00-04:00", finishedAt: "2026-04-15T00:05:00-04:00", recordsSeen: 12, message: "Drive strategy and operating artifacts indexed from MAB queries." },
  { id: "sync-google-workspace", source: "gmail", status: "warning", startedAt: "2026-04-15T00:05:00-04:00", finishedAt: "2026-04-15T00:06:00-04:00", recordsSeen: 8, message: "Gmail and Calendar snapshots are read-only until OAuth writeback is configured." },
  { id: "sync-cloudflare-live", source: "cloudflare", status: "success", startedAt: "2026-04-15T03:24:00-04:00", finishedAt: "2026-04-15T03:25:00-04:00", recordsSeen: 4, message: "Cloudflare Worker, D1, KV, Queue, Cron, and workers.dev sync gateway are live." },
];

export const initialOutbox: OutboxOperation[] = [
  {
    id: "outbox-sow-notion-link",
    source: "notion",
    collectionId: "collection://30ee7d75-e286-819b-9361-000b2c683069",
    recordId: "deal-sow-proposals",
    action: "update",
    field: "Deal Stage",
    value: "Active",
    createdAt: "2026-04-15T00:06:00-04:00",
    status: "blocked",
    note: "Ready after Notion OAuth token is configured in Cloudflare.",
  },
  {
    id: "outbox-gmail-label",
    source: "gmail",
    collectionId: "gmail-query:\"MAB AI Strategies\" newer_than:180d",
    recordId: "signal-gtm-chat",
    action: "label",
    field: "Labels",
    value: ["MAB/Strategy"],
    createdAt: "2026-04-15T00:06:00-04:00",
    status: "blocked",
    note: "Explicit-only Gmail action. The app will ask before applying labels.",
  },
];

export const initialConflicts: ConflictItem[] = [
  {
    id: "conflict-tool-secrets",
    source: "notion",
    collectionId: "collection://0f7b709d-f472-4883-af36-0c86b439e0d7",
    recordId: "tool-snov",
    field: "API Key",
    localValue: "redacted",
    remoteValue: "stored in Notion",
    detectedAt: "2026-04-15T00:06:00-04:00",
  },
];
